### ISSUE TITLE
Issue 2: User can turn their car

### ISSUE THREAD

**Issue by Boyul-Kim** [Boyul-Kim/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x]  create DOM elements
- [x] create event listener for arrow keys
- [x] event listeners should rotate the image based on arrow keys
